### ISSUE TITLE
Typo in conversion of water volume to mass

### ISSUE THREAD

**Issue by jgrooviest** [USEPA/ElectricityLCI#172] opened 2021-08-31 16:45 UTC
https://github.com/USEPA/ElectricityLCI/blob/2232c41f2cb4fd333ad59c8710aa55906e6a7ed3/electricitylci/hydro_upstream.py#L59

**Comment by jgrooviest** [comment] 2021-08-31 16:46
Could be fixing a typo in the original data.

**Comment by jump2conclusionsmatt** [comment] 2021-11-04 15:57
Duplicate of #153

**Closed** 2021-11-04 15:57 UTC
