### ISSUE TITLE
Some non-mapped emissions present

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/ElectricityLCI#59] opened 2019-10-04 01:36 UTC
All eGRID, TRI, and NEI emissions should be mapped to FEDEFL flows. Identify these and add them to the appropriate [flow mapping file](https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/tree/master/fedelemflowlist/flowmapping) in fedelemflowlist so that there are no emissions with compartments like 'air', 'soil' and 'water' which reflect original unmapped flows

**Comment by WesIngwersen** [comment] 2019-10-04 01:38
Created issues in fedelemflowlist based on ELCI_3 model ..where DIOXINS/water from TRI and Asbestos/air are not mapped

**Comment by jump2conclusionsmatt** [comment] 2019-10-23 19:17
Do we anticipate that this will be fixed before rolling everything out, or should I put in a quick fix to remove these from the inventories. The main consequence of these issues is that if you open a process in openlca that contains one of these flows, the inputs/outputs tab will not populate. The problem is that openLCA runs into a NULL in the flow refid. I've been taking care of this locally by running an SQL script in openLCA, but that's probably a bit much to ask of a user.

**Comment by WesIngwersen** [comment] 2019-10-23 20:35
@jump2conclusionsmatt I will add these two and create a new release to install that has them

**Comment by WesIngwersen** [comment] 2019-10-23 21:30
@jump2conclusionsmatt The master for fedelemflowlist now has these mappings added to it. See if that solves it

**Comment by jump2conclusionsmatt** [comment] 2019-10-24 13:53
This looks to be taken care of. Generated some results this morning and there are no longer any null f_flows in tbl_exchanges. I think this can be closed.

**Closed** 2019-10-24 19:42 UTC
